// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnimeController from "./anime_controller"
application.register("anime", AnimeController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LayoutsController from "./layouts_controller"
application.register("layouts", LayoutsController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import QuestionsController from "./questions_controller"
application.register("questions", QuestionsController)
